Added neuromorphism effect
tusharnankani/ToDoList pull request #20
Opened 2020-12-26 14:23 UTC by Whitedevil1206

Closes #7 
Pls check this PR .
I have checked it on my local pc and its working fine.

2020-12-26 15:14 UTC, tusharnankani commented
Hi @Whitedevil1206 
Could you attach a demonstration of how it looks like? You can share screenshots or record your screen. You can directly drag .mp4 files in here.

2020-12-26 18:20 UTC, Whitedevil1206 commented
Ok, i will send it tomorrow

2020-12-27 05:34 UTC, Whitedevil1206 commented
Hello this is the netlify link :
- [https://to-do-1.netlify.app/][https://to-do-1.netlify.app/]

2021-01-17 09:37 UTC, tusharnankani requested changes
Hi @Whitedevil1206 

Good work 👍🏻 
Apologies for the late review, was occupied with some commitments.

Also, with all due respect, after your sincere efforts, the end product might not look as good as we thought it would. Maybe, this to-do list web page is supposed to look simple after all, and neomorphic might not look as expected after all. But all that matters is trying and it counts.

Now, I would request you to play around more with neomorphic effects - since the website doesn't really look as appealing as we thought it would. 

https://user-images.githubusercontent.com/61280281/104836528-77229c00-58d4-11eb-9a19-c48dc1aea20d.mp4

- Play around with effects on all 3 buttons, try adding hover, and in-focus effects.
- As you have added a hover on input, you could add some inset, offset hover effects on the todos as well.

- Also here, could you try changing the color theme? The neomorphic effect doesn't really go well!
![image](https://user-images.githubusercontent.com/61280281/104836582-d97b9c80-58d4-11eb-8b45-a1f99d033453.png)

Appreciate your efforts! 💯

2025-01-27 16:22 UTC, closed without merging